import { Button, VerticalBox,HorizontalBox,Slider,GridBox,TextEdit } from "std-widgets.slint";

export AppWindow := Window {
	title: "Caculator";
	property <string> input : "" ;
	property <bool> number : false;
	property <bool> cannumber: true ;
	property <int> brackets : 0 ;
	callback caculate();
	callback caculater(string);
	caculater(getput) => { 
		output.text = getput;
	}
	VerticalBox { 
		if (brackets !=0) : Text{
			horizontal-alignment: center;
			text: "illegal";
			max-height: 20px;
			color: red;
		}
		TextEdit { 
			text: input;
			font-size: 20px;
			max-height: 200px;
			wrap: no-wrap;
			enabled: false;
		}
		output := TextEdit { 
			text: "";
			font-size: 20px;
			max-height: 100px;
			wrap: word-wrap;
			enabled: false;
		}

		// caculator
		GridBox { 
			Button { 
				col: 0;
				row: 0;
				text: "C";
				clicked => { 
					input = "";
					number = false;
					cannumber = true;
					brackets = 0;
				}
			}
			Button { 
				col: 1;
				row: 0;
				text: "/";
				clicked => {
					if(number) {
						input += "/";
						number = false;
						cannumber = true;
					}
				}
			}
			Button { 
				col: 2;
				row: 0;
				text: "*";
				clicked => { 
					if(number) {
						input += "*";
						number = false;
						cannumber = true;
					}
				}
			}

			Button { 
				col: 0;
				row: 1;
				text: "7";
				clicked => {
					if(cannumber) {
						input += "7";
						number = true;
					}
				}
			}
			Button { 
				col: 1;
				row: 1;
				text: "8";
				clicked => {
					if(cannumber) {
						input += "8";
						number = true;
					}
				}
			}
			Button { 
				col: 2;
				row: 1;
				text: "9";
				clicked => {
					if(cannumber) {
						input += "9" ;
						number = true;
					}
				}
			}
			Button { 
				col: 0;
				row: 2;
				text: "4";
				clicked => {
					if(cannumber) {
						input += "4";
						number = true;
					}
				}
			}
			Button { 
				col: 1;
				row: 2;
				text: "5";
				clicked => { 
					if(cannumber) {
						input += "5";
						number = true;
					}
				}
			}
			Button { 
				col: 2;
				row: 2;
				text: "6";
				clicked => { 
					if(cannumber) {
						input += "6";
						number = true;
					}
				}
			}
			Button { 
				col: 0;
				row: 3;
				text: "1";
				clicked => {
					if(cannumber) {
						input += "1";
						number = true;
					}
				}
			}
			Button { 
				col: 1;
				row: 3;
				text: "2";
				clicked => {
					if(cannumber) {
						input += "2";
						number = true;
					}
				}
			}
			Button { 
				col: 2;
				row: 3;
				text: "3";
				clicked => {
					if(cannumber) {
						input += "3";
						number = true;
					}
				}
			}
			Button { 
				col: 0;
				row: 4;
				text: "(";
				clicked => {
					if(!number) {
						brackets +=1;
						input += "(";
					}
				}
			}
			Button { 
				col: 1;
				//colspan: 3;
				row: 4;
				text: "0";
				clicked => {
					if(cannumber) {
						input += "0";
						number = true;
					}
				}
			}
			Button { 
				col: 2;
				//colspan: 3;
				row: 4;
				text: ")";
				clicked => { 
					if(brackets>0 && number) {
						input += ")";
						brackets -=1;
						cannumber = false;
					}
					
				}
			}
			Button { 
				col: 3;
				row: 0;
				text: "<-";
				clicked => { 
				}
			}
			Button { 
				col: 3;
				row: 1;
				text: "-";
				clicked => {
					if(number) {
						input += "-";
						number = false;
						cannumber = true;
					}
				}
			}
			Button { 
				col: 3;
				row: 2;
				text: "+";
				clicked => {
					if(number) {
						input += "+";
						number = false;
						cannumber = true;
					}
				}
			}
			Button { 
				col:3;
				row: 3;
				rowspan:2;
				text: "=";
				clicked => {
					if(brackets == 0) {
						caculate();
					}
				}
			}
		}
	}
}
